### PR TITLE
Kill threshold

### PR DESCRIPTION
**Pull request by rafaelri**
Make the JVMKill agent configurable in the sense that a single resourceExhausted event won't cause the JVM to be terminated.

Issues: #156

### CODE REVIEW

**Comment by rafaelri** [comment]
@nebhale I've decided to do the changes in increments. This commit covers the threshold (and a few tests for the agent). I did a regular C application to test the agent (without anything as fancy as cmocka but it seems to suffice). If you and @Zteve think it is fine we can move on with the thread dump. One thing to notice is that at least here in my tests the heapdump seems to be created by the VM itself. See the log I got while running a test that involves the VM and a custom crafted java class:
    ..........java.lang.OutOfMemoryError: Java heap space
    Dumping heap to java_pid21878.hprof ...
    Heap dump file created [2288332 bytes in 0,023 secs]
 Isn't it possible to have something collect that file (probably the script that already respawns the VM) ?

**Comment by rafaelri** [comment]
Forget the comment about the heapdump, it is the -XX:+HeapDumpOnOutOfMemoryError on the Makefile. My fault, coding and watching NHL probably leads to this...

**Comment by Zteve** [comment]
Hmm: I'm losing track of where the comments go.

Glyn Normington made the following comment on line 49 of `jvmkill.c`:

| _If the desired behaviour is that no more than count_threshold OOMs may occur in any period of 
| time_threshold seconds, then this code doesn't appear to achieve that. For instance, with a 
| time_threshold of 10 and count_threshold of 1, if 2 OOMs occur when `time(NULL)' is 99 and 100, 
| respectively, then it will appear as if the OOMs occurred in distinct 10-second intervals and the JVM 
| will not be killed when it should have been._

Any comments?

**Comment by glyn** [comment]
@rafaelri I tried to build this on Mac OS X and got:
```
$ make JAVA_HOME=$JAVA_HOME
==============================================
g++ -Wall -Werror -fPIC -std=c++11 -shared -fno-strict-aliasing -Wl,-soname=libJvmKill -static-libgcc  -fno-omit-frame-pointer -I"/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home//include" -I"/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home//include/darwin" -o libjvmkill.so jvmkill.c
clang: error: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
clang: error: unsupported option '-static-libgcc'
make: *** [build] Error 1
```
Any chance you could support Mac OS X?

**Comment by rafaelri** [comment]
@glyn probably not cause I am without a Mac right now. I have plans of
acquiring one but won't happen soon. :(

2016-02-29 9:44 GMT-03:00 Glyn Normington <notifications@github.com>:

**Comment by glyn** [comment]
@rafaelri Ok, thanks, I'll investigate.

**Comment by glyn** [comment]
@rafaelri This [commit](https://github.com/cloudfoundry/jvmkill/commit/4154d3ef6bfa62d20872b06109a4688db6a6022e) avoids compile/link errors and makes the tests pass on Mac OS X.

**Comment by glyn** [comment]
Also because I will only be spending one day per week on this, I made some notes in the wiki about [Mac OS Support](https://github.com/cloudfoundry/jvmkill/wiki/Mac-OS-X-Support).

**Comment by glyn** [comment]
@nebhale has confirmed that @rafaelri provided a CLA.

**Pull request merged**
